#!/usr/bin/env bash
# =============================================================================
# npm Supply Chain Attack — Compromise Checker
# Generated by npm-supply-chain-response skill
#
# Usage:
#   ./check_npm_compromise.sh <package_name> [--dry-run]
#
# This script checks whether a compromised npm package is installed in your
# environment, hunts for indicators of compromise, and offers guided
# remediation with confirmation prompts before any destructive action.
#
# Customize the variables in the CONFIGURATION section below for your specific
# incident before running.
# =============================================================================

set -euo pipefail

# --------------- CONFIGURATION — EDIT THESE FOR YOUR INCIDENT ----------------

# Compromised versions (space-separated)
COMPROMISED_VERSIONS="${COMPROMISED_VERSIONS:-1.14.1 0.30.4}"

# Last known safe version to pin to
SAFE_VERSION="${SAFE_VERSION:-1.14.0}"

# Attack window (UTC)
ATTACK_WINDOW_START="${ATTACK_WINDOW_START:-2026-03-31T00:00:00Z}"
ATTACK_WINDOW_END="${ATTACK_WINDOW_END:-2026-03-31T23:59:59Z}"

# Known C2 domains (space-separated, for log searching)
C2_DOMAINS="${C2_DOMAINS:-sfrclak.com}"

# Malicious dependency injected by the compromised package
MALICIOUS_DEP="${MALICIOUS_DEP:-plain-crypto-js}"

# Known persistence paths (space-separated) — platform-specific
PERSISTENCE_PATHS_MACOS="${PERSISTENCE_PATHS_MACOS:-/Library/Caches/com.apple.act.mond}"
PERSISTENCE_PATHS_LINUX="${PERSISTENCE_PATHS_LINUX:-/tmp/ld.py}"

# ----------------------------- END CONFIGURATION -----------------------------

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Globals
PACKAGE="${1:-}"
DRY_RUN=false
FINDINGS=()
ACTIONS_TAKEN=()

for arg in "$@"; do
    if [[ "$arg" == "--dry-run" ]]; then
        DRY_RUN=true
    fi
done

# ---- Helpers ----------------------------------------------------------------

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()      { echo -e "${GREEN}[OK]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
finding() { echo -e "${RED}[FINDING]${NC} $*"; FINDINGS+=("$*"); }

confirm() {
    if $DRY_RUN; then
        info "(dry-run) Would prompt: $1"
        return 1
    fi
    read -rp "$(echo -e "${YELLOW}$1 [y/N]: ${NC}")" answer
    [[ "$answer" =~ ^[Yy] ]]
}

# ---- Preflight --------------------------------------------------------------

if [[ -z "$PACKAGE" ]]; then
    echo "Usage: $0 <package_name> [--dry-run]"
    echo "       $0 axios"
    echo "       $0 axios --dry-run"
    exit 1
fi

echo ""
echo -e "${BOLD}=== npm Supply Chain Compromise Checker ===${NC}"
echo -e "Package:     ${BOLD}$PACKAGE${NC}"
echo -e "Bad versions: ${BOLD}$COMPROMISED_VERSIONS${NC}"
echo -e "Safe version: ${BOLD}$SAFE_VERSION${NC}"
echo -e "Malicious dep: ${BOLD}$MALICIOUS_DEP${NC}"
echo -e "C2 domains:  ${BOLD}$C2_DOMAINS${NC}"
echo -e "Mode:        ${BOLD}$(if $DRY_RUN; then echo 'DRY RUN'; else echo 'LIVE'; fi)${NC}"
echo ""

# ---- Phase 1: Exposure Check ------------------------------------------------

echo -e "${BOLD}--- Phase 1: Exposure Check ---${NC}"

# Check lockfiles
LOCKFILES=("package-lock.json" "yarn.lock" "pnpm-lock.yaml")
for lf in "${LOCKFILES[@]}"; do
    if [[ -f "$lf" ]]; then
        if grep -q "$PACKAGE" "$lf" 2>/dev/null; then
            info "Found $PACKAGE in $lf"
            # Check for compromised versions
            for ver in $COMPROMISED_VERSIONS; do
                if grep -q "$ver" "$lf" 2>/dev/null; then
                    finding "Compromised version $ver found in $lf"
                fi
            done
        else
            ok "$PACKAGE not found in $lf"
        fi
    fi
done

# Check for malicious dependency in lockfiles
for lf in "${LOCKFILES[@]}"; do
    if [[ -f "$lf" ]]; then
        if grep -q "$MALICIOUS_DEP" "$lf" 2>/dev/null; then
            finding "Malicious dependency $MALICIOUS_DEP found in $lf"
        fi
    fi
done

# Check node_modules
if [[ -d "node_modules/$PACKAGE" ]]; then
    INSTALLED_VERSION=$(cat "node_modules/$PACKAGE/package.json" 2>/dev/null | grep '"version"' | head -1 | sed 's/.*: *"//;s/".*//')
    info "Installed version: $INSTALLED_VERSION"
    for ver in $COMPROMISED_VERSIONS; do
        if [[ "$INSTALLED_VERSION" == "$ver" ]]; then
            finding "Compromised version $ver is currently installed in node_modules"
        fi
    done
else
    ok "$PACKAGE not found in node_modules/"
fi

# Check for malicious dependency in node_modules
if [[ -d "node_modules/$MALICIOUS_DEP" ]]; then
    finding "Malicious dependency $MALICIOUS_DEP found in node_modules/"
else
    ok "$MALICIOUS_DEP not in node_modules/"
fi

# Check npm cache
if grep -rq "$MALICIOUS_DEP" ~/.npm/_cacache/index-v5/ 2>/dev/null; then
    finding "$MALICIOUS_DEP found in npm cache (~/.npm/_cacache/)"
else
    ok "$MALICIOUS_DEP not found in npm cache"
fi

echo ""

# ---- Phase 2: IOC Hunting ----------------------------------------------------

echo -e "${BOLD}--- Phase 2: IOC Hunting ---${NC}"

# Anti-forensics: package.md swap
if [[ -f "node_modules/$MALICIOUS_DEP/package.md" ]]; then
    finding "Anti-forensics detected: package.md found in $MALICIOUS_DEP (payload already executed and cleaned up)"
fi

# Check for self-deleted setup.js
if [[ -d "node_modules/$MALICIOUS_DEP" ]] && [[ ! -f "node_modules/$MALICIOUS_DEP/setup.js" ]]; then
    warn "setup.js missing from $MALICIOUS_DEP — may have self-deleted after execution"
fi

# Postinstall scripts in all packages
SUSPICIOUS_POSTINSTALL=$(find node_modules -maxdepth 2 -name package.json -exec grep -l '"postinstall"' {} \; 2>/dev/null | head -20)
if [[ -n "$SUSPICIOUS_POSTINSTALL" ]]; then
    warn "Packages with postinstall scripts:"
    echo "$SUSPICIOUS_POSTINSTALL" | while read -r f; do
        echo "  $f"
    done
fi

# Platform-specific IOCs
OS_TYPE=$(uname -s 2>/dev/null || echo "Unknown")
case "$OS_TYPE" in
    Darwin)
        for p in $PERSISTENCE_PATHS_MACOS; do
            if [[ -e "$p" ]]; then
                finding "macOS IOC found: $p"
            else
                ok "macOS IOC not found: $p"
            fi
        done
        ;;
    Linux)
        for p in $PERSISTENCE_PATHS_LINUX; do
            if [[ -e "$p" ]]; then
                finding "Linux IOC found: $p"
            else
                ok "Linux IOC not found: $p"
            fi
        done
        # Check systemd persistence
        if find ~/.config/systemd/user/ -name "*.service" -mtime -7 2>/dev/null | grep -q .; then
            warn "Recent systemd user services found — review manually"
        fi
        ;;
esac

# Network IOCs
for domain in $C2_DOMAINS; do
    if ss -tnp 2>/dev/null | grep -qi "$domain"; then
        finding "Active connection to C2 domain: $domain"
    fi
    if grep -rqF "$domain" /var/log/ 2>/dev/null; then
        finding "C2 domain $domain found in /var/log/"
    fi
done

# Process check
if ps aux 2>/dev/null | grep -E "ld\.py|com\.apple\.act|wt\.exe" | grep -v grep | grep -q .; then
    finding "Suspicious process found — possible payload execution"
fi

# Credential access check
for f in ~/.ssh/id_rsa ~/.ssh/id_ed25519 ~/.npmrc ~/.aws/credentials; do
    if [[ -f "$f" ]]; then
        ATIME=$(stat -c %X "$f" 2>/dev/null || stat -f %a "$f" 2>/dev/null)
        if [[ -n "$ATIME" ]]; then
            NOW=$(date +%s)
            DIFF=$((NOW - ATIME))
            if [[ $DIFF -lt 86400 ]]; then
                warn "Recent access on $f (within last 24h) — may indicate credential harvesting"
            fi
        fi
    fi
done

echo ""

# ---- Phase 3: Containment ---------------------------------------------------

echo -e "${BOLD}--- Phase 3: Containment ---${NC}"

if [[ ${#FINDINGS[@]} -eq 0 ]]; then
    ok "No indicators of compromise found. Your environment appears clean."
    echo ""
    echo -e "${GREEN}${BOLD}=== Result: CLEAN ===${NC}"
    echo "No compromised versions or IOCs detected."
    echo "Continue to monitor advisories for $PACKAGE."
    exit 0
fi

echo -e "${RED}${BOLD}Found ${#FINDINGS[@]} indicator(s) of compromise:${NC}"
for f in "${FINDINGS[@]}"; do
    echo -e "  ${RED}•${NC} $f"
done
echo ""

# Remove malicious dependency
if [[ -d "node_modules/$MALICIOUS_DEP" ]]; then
    if confirm "Remove malicious dependency node_modules/$MALICIOUS_DEP?"; then
        rm -rf "node_modules/$MALICIOUS_DEP"
        ACTIONS_TAKEN+=("Removed node_modules/$MALICIOUS_DEP")
        ok "Removed $MALICIOUS_DEP"
    fi
fi

# Purge npm cache
if confirm "Purge npm cache to remove cached malicious packages?"; then
    npm cache clean --force 2>/dev/null
    ACTIONS_TAKEN+=("Purged npm cache")
    ok "npm cache purged"
fi

# Pin safe version
if confirm "Pin $PACKAGE to safe version $SAFE_VERSION?"; then
    npm install "$PACKAGE@$SAFE_VERSION" --save-exact 2>/dev/null
    ACTIONS_TAKEN+=("Pinned $PACKAGE@$SAFE_VERSION")
    ok "Pinned to $PACKAGE@$SAFE_VERSION"
fi

# Remove platform-specific IOCs
case "$OS_TYPE" in
    Darwin)
        for p in $PERSISTENCE_PATHS_MACOS; do
            if [[ -e "$p" ]]; then
                if confirm "Remove macOS IOC: $p?"; then
                    rm -f "$p"
                    ACTIONS_TAKEN+=("Removed $p")
                    ok "Removed $p"
                fi
            fi
        done
        ;;
    Linux)
        for p in $PERSISTENCE_PATHS_LINUX; do
            if [[ -e "$p" ]]; then
                if confirm "Remove Linux IOC: $p?"; then
                    rm -f "$p"
                    ACTIONS_TAKEN+=("Removed $p")
                    ok "Removed $p"
                fi
            fi
        done
        ;;
esac

echo ""

# ---- Summary ----------------------------------------------------------------

echo -e "${BOLD}=== Summary ===${NC}"
echo ""
echo -e "${RED}Findings (${#FINDINGS[@]}):${NC}"
for f in "${FINDINGS[@]}"; do
    echo "  • $f"
done

if [[ ${#ACTIONS_TAKEN[@]} -gt 0 ]]; then
    echo ""
    echo -e "${GREEN}Actions taken (${#ACTIONS_TAKEN[@]}):${NC}"
    for a in "${ACTIONS_TAKEN[@]}"; do
        echo "  • $a"
    done
fi

echo ""
echo -e "${YELLOW}${BOLD}IMPORTANT: Credential rotation is required.${NC}"
echo "All secrets, tokens, and credentials accessible on this system should be"
echo "considered compromised. Use the credential-exfiltration-response skill"
echo "or rotate manually: SSH keys, cloud credentials, npm tokens, .env secrets."
echo ""
